#include "core/cpu6502_tables.h"
#include "core/cpu6502.h"

const instruction_t cpu_lookup[256] = {
    {"BRK", cpu_BRK, cpu_IMM, 7 },{ "ORA", cpu_ORA, cpu_IZX, 6 },{ "???", cpu_XXX, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 8 },{ "???", cpu_NOP, cpu_IMP, 3 },{ "ORA", cpu_ORA, cpu_ZP0, 3 },{ "ASL", cpu_ASL, cpu_ZP0, 5 },{ "???", cpu_XXX, cpu_IMP, 5 },{ "PHP", cpu_PHP, cpu_IMP, 3 },{ "ORA", cpu_ORA, cpu_IMM, 2 },{ "ASL", cpu_ASL, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 2 },{ "???", cpu_NOP, cpu_IMP, 4 },{ "ORA", cpu_ORA, cpu_ABS, 4 },{ "ASL", cpu_ASL, cpu_ABS, 6 },{ "???", cpu_XXX, cpu_IMP, 6 },
    { "BPL", cpu_BPL, cpu_REL, 2 },{ "ORA", cpu_ORA, cpu_IZY, 5 },{ "???", cpu_XXX, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 8 },{ "???", cpu_NOP, cpu_IMP, 4 },{ "ORA", cpu_ORA, cpu_ZPX, 4 },{ "ASL", cpu_ASL, cpu_ZPX, 6 },{ "???", cpu_XXX, cpu_IMP, 6 },{ "CLC", cpu_CLC, cpu_IMP, 2 },{ "ORA", cpu_ORA, cpu_ABY, 4 },{ "???", cpu_NOP, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 7 },{ "???", cpu_NOP, cpu_IMP, 4 },{ "ORA", cpu_ORA, cpu_ABX, 4 },{ "ASL", cpu_ASL, cpu_ABX, 7 },{ "???", cpu_XXX, cpu_IMP, 7 },
    { "JSR", cpu_JSR, cpu_ABS, 6 },{ "AND", cpu_AND, cpu_IZX, 6 },{ "???", cpu_XXX, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 8 },{ "BIT", cpu_BIT, cpu_ZP0, 3 },{ "AND", cpu_AND, cpu_ZP0, 3 },{ "ROL", cpu_ROL, cpu_ZP0, 5 },{ "???", cpu_XXX, cpu_IMP, 5 },{ "PLP", cpu_PLP, cpu_IMP, 4 },{ "AND", cpu_AND, cpu_IMM, 2 },{ "ROL", cpu_ROL, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 2 },{ "BIT", cpu_BIT, cpu_ABS, 4 },{ "AND", cpu_AND, cpu_ABS, 4 },{ "ROL", cpu_ROL, cpu_ABS, 6 },{ "???", cpu_XXX, cpu_IMP, 6 },
    { "BMI", cpu_BMI, cpu_REL, 2 },{ "AND", cpu_AND, cpu_IZY, 5 },{ "???", cpu_XXX, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 8 },{ "???", cpu_NOP, cpu_IMP, 4 },{ "AND", cpu_AND, cpu_ZPX, 4 },{ "ROL", cpu_ROL, cpu_ZPX, 6 },{ "???", cpu_XXX, cpu_IMP, 6 },{ "SEC", cpu_SEC, cpu_IMP, 2 },{ "AND", cpu_AND, cpu_ABY, 4 },{ "???", cpu_NOP, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 7 },{ "???", cpu_NOP, cpu_IMP, 4 },{ "AND", cpu_AND, cpu_ABX, 4 },{ "ROL", cpu_ROL, cpu_ABX, 7 },{ "???", cpu_XXX, cpu_IMP, 7 },
    { "RTI", cpu_RTI, cpu_IMP, 6 },{ "EOR", cpu_EOR, cpu_IZX, 6 },{ "???", cpu_XXX, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 8 },{ "???", cpu_NOP, cpu_IMP, 3 },{ "EOR", cpu_EOR, cpu_ZP0, 3 },{ "LSR", cpu_LSR, cpu_ZP0, 5 },{ "???", cpu_XXX, cpu_IMP, 5 },{ "PHA", cpu_PHA, cpu_IMP, 3 },{ "EOR", cpu_EOR, cpu_IMM, 2 },{ "LSR", cpu_LSR, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 2 },{ "JMP", cpu_JMP, cpu_ABS, 3 },{ "EOR", cpu_EOR, cpu_ABS, 4 },{ "LSR", cpu_LSR, cpu_ABS, 6 },{ "???", cpu_XXX, cpu_IMP, 6 },
    { "BVC", cpu_BVC, cpu_REL, 2 },{ "EOR", cpu_EOR, cpu_IZY, 5 },{ "???", cpu_XXX, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 8 },{ "???", cpu_NOP, cpu_IMP, 4 },{ "EOR", cpu_EOR, cpu_ZPX, 4 },{ "LSR", cpu_LSR, cpu_ZPX, 6 },{ "???", cpu_XXX, cpu_IMP, 6 },{ "CLI", cpu_CLI, cpu_IMP, 2 },{ "EOR", cpu_EOR, cpu_ABY, 4 },{ "???", cpu_NOP, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 7 },{ "???", cpu_NOP, cpu_IMP, 4 },{ "EOR", cpu_EOR, cpu_ABX, 4 },{ "LSR", cpu_LSR, cpu_ABX, 7 },{ "???", cpu_XXX, cpu_IMP, 7 },
    { "RTS", cpu_RTS, cpu_IMP, 6 },{ "ADC", cpu_ADC, cpu_IZX, 6 },{ "???", cpu_XXX, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 8 },{ "???", cpu_NOP, cpu_IMP, 3 },{ "ADC", cpu_ADC, cpu_ZP0, 3 },{ "ROR", cpu_ROR, cpu_ZP0, 5 },{ "???", cpu_XXX, cpu_IMP, 5 },{ "PLA", cpu_PLA, cpu_IMP, 4 },{ "ADC", cpu_ADC, cpu_IMM, 2 },{ "ROR", cpu_ROR, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 2 },{ "JMP", cpu_JMP, cpu_IND, 5 },{ "ADC", cpu_ADC, cpu_ABS, 4 },{ "ROR", cpu_ROR, cpu_ABS, 6 },{ "???", cpu_XXX, cpu_IMP, 6 },
    { "BVS", cpu_BVS, cpu_REL, 2 },{ "ADC", cpu_ADC, cpu_IZY, 5 },{ "???", cpu_XXX, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 8 },{ "???", cpu_NOP, cpu_IMP, 4 },{ "ADC", cpu_ADC, cpu_ZPX, 4 },{ "ROR", cpu_ROR, cpu_ZPX, 6 },{ "???", cpu_XXX, cpu_IMP, 6 },{ "SEI", cpu_SEI, cpu_IMP, 2 },{ "ADC", cpu_ADC, cpu_ABY, 4 },{ "???", cpu_NOP, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 7 },{ "???", cpu_NOP, cpu_IMP, 4 },{ "ADC", cpu_ADC, cpu_ABX, 4 },{ "ROR", cpu_ROR, cpu_ABX, 7 },{ "???", cpu_XXX, cpu_IMP, 7 },
    { "???", cpu_NOP, cpu_IMP, 2 },{ "STA", cpu_STA, cpu_IZX, 6 },{ "???", cpu_NOP, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 6 },{ "STY", cpu_STY, cpu_ZP0, 3 },{ "STA", cpu_STA, cpu_ZP0, 3 },{ "STX", cpu_STX, cpu_ZP0, 3 },{ "???", cpu_XXX, cpu_IMP, 3 },{ "DEY", cpu_DEY, cpu_IMP, 2 },{ "???", cpu_NOP, cpu_IMP, 2 },{ "TXA", cpu_TXA, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 2 },{ "STY", cpu_STY, cpu_ABS, 4 },{ "STA", cpu_STA, cpu_ABS, 4 },{ "STX", cpu_STX, cpu_ABS, 4 },{ "???", cpu_XXX, cpu_IMP, 4 },
    { "BCC", cpu_BCC, cpu_REL, 2 },{ "STA", cpu_STA, cpu_IZY, 6 },{ "???", cpu_XXX, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 6 },{ "STY", cpu_STY, cpu_ZPX, 4 },{ "STA", cpu_STA, cpu_ZPX, 4 },{ "STX", cpu_STX, cpu_ZPY, 4 },{ "???", cpu_XXX, cpu_IMP, 4 },{ "TYA", cpu_TYA, cpu_IMP, 2 },{ "STA", cpu_STA, cpu_ABY, 5 },{ "TXS", cpu_TXS, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 5 },{ "???", cpu_NOP, cpu_IMP, 5 },{ "STA", cpu_STA, cpu_ABX, 5 },{ "???", cpu_XXX, cpu_IMP, 5 },{ "???", cpu_XXX, cpu_IMP, 5 },
    { "LDY", cpu_LDY, cpu_IMM, 2 },{ "LDA", cpu_LDA, cpu_IZX, 6 },{ "LDX", cpu_LDX, cpu_IMM, 2 },{ "???", cpu_XXX, cpu_IMP, 6 },{ "LDY", cpu_LDY, cpu_ZP0, 3 },{ "LDA", cpu_LDA, cpu_ZP0, 3 },{ "LDX", cpu_LDX, cpu_ZP0, 3 },{ "???", cpu_XXX, cpu_IMP, 3 },{ "TAY", cpu_TAY, cpu_IMP, 2 },{ "LDA", cpu_LDA, cpu_IMM, 2 },{ "TAX", cpu_TAX, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 2 },{ "LDY", cpu_LDY, cpu_ABS, 4 },{ "LDA", cpu_LDA, cpu_ABS, 4 },{ "LDX", cpu_LDX, cpu_ABS, 4 },{ "???", cpu_XXX, cpu_IMP, 4 },
    { "BCS", cpu_BCS, cpu_REL, 2 },{ "LDA", cpu_LDA, cpu_IZY, 5 },{ "???", cpu_XXX, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 5 },{ "LDY", cpu_LDY, cpu_ZPX, 4 },{ "LDA", cpu_LDA, cpu_ZPX, 4 },{ "LDX", cpu_LDX, cpu_ZPY, 4 },{ "???", cpu_XXX, cpu_IMP, 4 },{ "CLV", cpu_CLV, cpu_IMP, 2 },{ "LDA", cpu_LDA, cpu_ABY, 4 },{ "TSX", cpu_TSX, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 4 },{ "LDY", cpu_LDY, cpu_ABX, 4 },{ "LDA", cpu_LDA, cpu_ABX, 4 },{ "LDX", cpu_LDX, cpu_ABY, 4 },{ "???", cpu_XXX, cpu_IMP, 4 },
    { "CPY", cpu_CPY, cpu_IMM, 2 },{ "CMP", cpu_CMP, cpu_IZX, 6 },{ "???", cpu_NOP, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 8 },{ "CPY", cpu_CPY, cpu_ZP0, 3 },{ "CMP", cpu_CMP, cpu_ZP0, 3 },{ "DEC", cpu_DEC, cpu_ZP0, 5 },{ "???", cpu_XXX, cpu_IMP, 5 },{ "INY", cpu_INY, cpu_IMP, 2 },{ "CMP", cpu_CMP, cpu_IMM, 2 },{ "DEX", cpu_DEX, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 2 },{ "CPY", cpu_CPY, cpu_ABS, 4 },{ "CMP", cpu_CMP, cpu_ABS, 4 },{ "DEC", cpu_DEC, cpu_ABS, 6 },{ "???", cpu_XXX, cpu_IMP, 6 },
    { "BNE", cpu_BNE, cpu_REL, 2 },{ "CMP", cpu_CMP, cpu_IZY, 5 },{ "???", cpu_XXX, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 8 },{ "???", cpu_NOP, cpu_IMP, 4 },{ "CMP", cpu_CMP, cpu_ZPX, 4 },{ "DEC", cpu_DEC, cpu_ZPX, 6 },{ "???", cpu_XXX, cpu_IMP, 6 },{ "CLD", cpu_CLD, cpu_IMP, 2 },{ "CMP", cpu_CMP, cpu_ABY, 4 },{ "NOP", cpu_NOP, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 7 },{ "???", cpu_NOP, cpu_IMP, 4 },{ "CMP", cpu_CMP, cpu_ABX, 4 },{ "DEC", cpu_DEC, cpu_ABX, 7 },{ "???", cpu_XXX, cpu_IMP, 7 },
    { "CPX", cpu_CPX, cpu_IMM, 2 },{ "SBC", cpu_SBC, cpu_IZX, 6 },{ "???", cpu_NOP, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 8 },{ "CPX", cpu_CPX, cpu_ZP0, 3 },{ "SBC", cpu_SBC, cpu_ZP0, 3 },{ "INC", cpu_INC, cpu_ZP0, 5 },{ "???", cpu_XXX, cpu_IMP, 5 },{ "INX", cpu_INX, cpu_IMP, 2 },{ "SBC", cpu_SBC, cpu_IMM, 2 },{ "NOP", cpu_NOP, cpu_IMP, 2 },{ "???", cpu_SBC, cpu_IMP, 2 },{ "CPX", cpu_CPX, cpu_ABS, 4 },{ "SBC", cpu_SBC, cpu_ABS, 4 },{ "INC", cpu_INC, cpu_ABS, 6 },{ "???", cpu_XXX, cpu_IMP, 6 },
    { "BEQ", cpu_BEQ, cpu_REL, 2 },{ "SBC", cpu_SBC, cpu_IZY, 5 },{ "???", cpu_XXX, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 8 },{ "???", cpu_NOP, cpu_IMP, 4 },{ "SBC", cpu_SBC, cpu_ZPX, 4 },{ "INC", cpu_INC, cpu_ZPX, 6 },{ "???", cpu_XXX, cpu_IMP, 6 },{ "SED", cpu_SED, cpu_IMP, 2 },{ "SBC", cpu_SBC, cpu_ABY, 4 },{ "NOP", cpu_NOP, cpu_IMP, 2 },{ "???", cpu_XXX, cpu_IMP, 7 },{ "???", cpu_NOP, cpu_IMP, 4 },{ "SBC", cpu_SBC, cpu_ABX, 4 },{ "INC", cpu_INC, cpu_ABX, 7 },{ "???", cpu_XXX, cpu_IMP, 7 }
};